config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :questions do
    collection do
      get :autocomplete
      get :search
    end

    resources :answers, except: [:index, :new]
  end

  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(ENV["SK_USER"])
    ) &
    ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(ENV["SK_PASS"])
      )
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Friendlyable

  belongs_to :question
  belongs_to :user

  validates :body, :presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/friendlyable.rb
module Friendlyable
  extend ActiveSupport::Concern

  included do
    extend ::FriendlyId
    before_create :set_hash_id
    friendly_id :hash_id
  end

  def set_hash_id
    hash_id = nil

    loop do
      hash_id = SecureRandom.urlsafe_base64(9).gsub(/-|_/, ('a'..'z')
            .to_a[rand(26)])
      break unless self.class.name.constantize.where(:hash_id => hash_id).exists?
    end
    self.hash_id = hash_id
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Friendlyable
  belongs_to :user
  has_many :answers, -> { order("created_at DESC") }, dependent: :delete_all

  validates :title, :presence => true
  validates :body, :presence => true

  searchkick  text_start: [:title]

  def search_data
    {
      title: title,
      body: body
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable,
         :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(auth)
    user = find_by(uid: auth[:uid]) || User.new

    user.attributes = {
      provider: auth[:provider],
      uid: auth[:uid],
      email: auth[:info][:email],
      password: Devise.friendly_token[0,20],
      first_name: auth[:info][:first_name],
      last_name: auth[:info][:last_name],
      token: auth[:credentials][:token],
      refresh_token: auth[:credentials][:refresh_token],
      oauth_expires_at: auth[:credentials][:expires_at]
    }

    user.save!

    user
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: [:create, :edit, :update, :destroy]
  before_action :set_answer, only: [:edit, :update, :destroy]


  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user

    if @answer.save
      invoke_cables
      redirect_to question_path(@question), notice: "Your answer was added."
    else
      @answers = @question.answers.reload
      render 'questions/show'
    end
  end

  def edit; end

  def update
    if @answer.update(answer_params)
      redirect_to question_path(@question), notice: 'Your answer was updated.'
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to question_path(@question), notice: 'Your answer was deleted.'
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def invoke_cables
    CableServices::NotifyJobsService.(
      question: @question,
      current_user_id: current_user.id
    )
  end

  def set_question
    @question = Question.find_by(hash_id: params[:question_id])
  end

  def set_answer
    @answer = Answer.find_by(hash_id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question
                  .order(created_at: :desc)
                  .page(params[:page])
                  .per(5)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      flash[:notice] = 'Question was successfully created.'
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @answer = Answer.new
    @answers = @question.reload.answers
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: "This question was updated."
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to root_path, notice: "Question was successfully destroyed."
  end

  def autocomplete
    render json: Question.search(params[:term], fields: [{title: :text_start}], limit: 10).map(&:title)
  end

  def search
    query = params[:q].presence || "*"
    @questions = Question.search(query)
  end

  private

  def set_question
    @question = Question.find_by(hash_id: params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    @auth = request.env['omniauth.auth']

    if successful_integration_creation
      sign_in(@user, scope: @user)
      redirect_to root_path, notice: 'Signed in successfully.'
    else
      redirect_to user_session_path, alert: 'Google was unable to authorize this request. Please try again.'
    end
  end

  private

  def create_user
    @user = User.from_omniauth(@auth)
  end

  def successful_integration_creation
    @auth != :invalid_credentials &&
              @auth[:credentials][:token] &&
              create_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    # return if flash[0][0] == :form_error
    flash.each do |msg_type, message|
      next if msg_type == :form_error
      concat(content_tag(:div, message.html_safe, {
        class: "alert #{bootstrap_class_for(msg_type)} fade in"}) do
        concat content_tag(:button, 'x', class: "close", data: {
          dismiss: 'alert'
          })
        concat message.html_safe
        end)
    end
    nil
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def to_markdown(content)
    pipeline_context = { gfm: true, asset_root: "https://a248.e.akamai.net/assets.github.com/images/icons" }
    pipeline = HTML::Pipeline.new [
      HTML::Pipeline::MarkdownFilter,
      HTML::Pipeline::EmojiFilter,
      HTML::Pipeline::SanitizationFilter,
    ], pipeline_context
    pipeline.call(content)[:output].to_s.html_safe
  end
end

app/views/answers/_answer.html.erb
<em>
  <% if answer.user == current_user %>
    <%= link_to("edit", edit_question_answer_path(question, answer)) %>
    <%= link_to "delete", question_answer_path(question, answer), { method: :delete, data: { confirm: "Are you sure" } } %>
  <% end %>
  <%= to_markdown answer.body %> </em>

<small><%= answer.user.first_name %> <%= answer.created_at.strftime("on %m/%d/%Y %l:%M%P") %></small>
<hr>

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
  <%= render :partial => "shared/model_errors", locals: { model: @answer } %>

  <%= f.text_area :body, placeholder: "Answer... markdown and emoji supported", rows: 4, cols: 50 %>

  <br>

  <%= f.submit "submit answer"%>

<% end %>

app/views/answers/edit.html.erb
<p>
  Edit Answer
</p>

<%= render 'form'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QAndA</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= flash_messages %>
        <p>
          Hello, <%= current_user.first_name %>
          <%= link_to("Q n A", root_path) %> |
          <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        </p>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QAndA</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= flash_messages %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/questions/_answers.html.erb
<% if answers.empty? %>
  <em class="text-muted">No answers yet. Be the first to answer this question</em>
<% end %>

<% answers.each do |answer| %>
  <%= render partial: 'answers/answer', locals: { answer: answer,
                                                  question: question,
                                                  current_user: current_user} %>
<% end %>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

  <% if @question.errors.any? %>
    <%= render :partial => "shared/model_errors", locals: { model: @question } %>
  <% end %>

  <div class="row">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: "Title", class: "form-control"  %>
    </div>
  </div>

  <div class="row">
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, placeholder: "Question... markdown and emoji supported", rows: 8, class: "form-control"  %>
    </div>
  </div>

  <div class="row">
    <div class="form-group">
      <%= f.submit @question.new_record? ? "Add question" : "Update question", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div class="box-body">
  <li><%= question.title %>
  <small>asked by <%= question.user.first_name %> <%= question.created_at.strftime("on %m/%d/%Y %l:%M%P") %></small>
  </li>

  <small>
    <span>
      <%= link_to("#{question.answers.size} answers", question_path(question)) %>
    </span>
  </small>

  <hr>
</div>

app/views/questions/edit.html.erb
<h2>
  Edit question
</h2>

<%= render "form" %>

app/views/questions/index.html.erb
<%= link_to new_question_path do %>
  <button>add new question</button>
<% end %>

<h2>
  All Question
</h2>

<%= form_tag search_questions_path, method: :get do %>
  <%= text_field_tag :q, nil, placeholder: 'Search...'  %>
<% end %>

<hr>

<% if @questions.empty? %>
  <p>No questions are available to display</p>
<% end %>

<ul>
  <% @questions.each do |question| %>
    <%= render 'question', question: question  %>
  <% end %>
</ul>

<%= paginate @questions %>

app/views/questions/new.html.erb
<h2>
  Add a Question
</h2>

<%= render 'form' %>

app/views/questions/search.html.erb
<p>
  <%= pluralize(@questions.size, 'result') %> found
</p>

<ul>
  <% @questions.each do |question| %>
    <%= render 'question', question: question  %>
  <% end %>
</ul>

app/views/questions/show.html.erb
<hr>

<% if @question.user == current_user %>
  <%= link_to "edit", edit_question_path(@question) %>
  |
  <%= link_to "delete", question_path(@question), { method: :delete, data: { confirm: "Are you sure" } }  %>
<% end %>

<h1><%= @question.title  %></h1>

<%= to_markdown @question.body %>

<hr>

<%= render partial: 'answers/form' %>

<h5>Answers:</h5>

<div id="answers-container">
  <%= render partial: 'questions/answers', locals: { answers: @answers, question: @question } %>
</div>

app/views/shared/_model_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <button class="close" data-dismiss="alert" type="button">x</button>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>